### ISSUE TITLE
[Archi] Changer la logique de cache du site

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#1303]
Avec la disparition des cookies stickys, et les caches existants côté API Entreprise, et API Recherche, on peut essayer de changer la logique de cache : 
- [x] annuaire-entreprises-data-gouv-fr/search-api#429
- [x] annuaire-entreprises-data-gouv-fr/infrastructure#237
- [x] annuaire-entreprises-data-gouv-fr/api-proxy#27
- [x] annuaire-entreprises-data-gouv-fr/infrastructure#240
- [x] annuaire-entreprises-data-gouv-fr/site#1304
- [x] annuaire-entreprises-data-gouv-fr/infrastructure#236

**Comment by XavierJp** [comment]
Quand je coche une case c'est que les PR sont pretes

**Comment by MKCG** [comment]
> Quand je coche une case c'est que les PR sont pretes

Idem, pour la suppression du redis du site : il faudra attendre d'avoir mis en prod les autres tickets et d'en être satisfait avant de mettre à jour l'infra

**Comment by XavierJp** [comment]
@MKCG should we close this ?

**Comment by MKCG** [comment]
> @MKCG should we close this ?

Ok. La partie infra sera déployée lors de la mise à disposition des serveurs OVH
